{!! Minify::javascript(array('/assets/js/jquery-1.10.2.min.js',
                             '/assets/js/jquery.validate.js',
                             '/assets/js/html5shiv.js',
                             '/assets/js/respond.min.js',
                             '/bower_components/jquery/dist/jquery.min.js',
                             '/bower_components/jquery/dist/jquery.validate.min.js',
                             '/assets/js/jquery-ui-1-10-4.js',
                             '/assets/js/select2.min.js',
                             '/js/jquery.tokeninput.js',
                             '/js/bootstrap-timepicker.min.js',
                             '/js/moment.js',
                             '/js/bootstrap-datepicker.js',
                             '/bower_components/bootstrap/dist/js/bootstrap-datepicker.min.js',
                             '/js/dataTables.jqueryui.js',
                             '/assets/js/jqueryui-1.11.4.min.js',
                             '/bower_components/bootstrap/dist/js/bootstrap.min.js',
                             '/bower_components/metisMenu/dist/metisMenu.min.js',
                             '/bower_components/morrisjs/morris.min.js',
                             '/bower_components/raphael/raphael-min.js',
                             '/dist/js/sb-admin-2.js',
                             '/assets/js/custom.js',
                             '/js/tableHeadFixer.js',
                            )) !!}