{!! Minify::stylesheet(array('/bower_components/bootstrap/dist/css/bootstrap.min.css',
                            '/css/dataTables.jqueryui.css',
                            '/assets/css/select2.css',
                            '/bower_components/metisMenu/dist/metisMenu.min.css',
                            '/dist/css/timeline.css',
                            '/dist/css/sb-admin-2.css',
                            '/assets/js/morris/morris.css',
                            '/bower_components/font-awesome/css/font-awesome.min.css',
                            '/css/default.css',
                            '/assets/css/custom.css',
                            '/css/datepicker.css',
                            '/assets/css/jquery-ui-1-8.css',
                            '/css/bootstrap-timepicker.min.css',
                            '/css/datetimepicker.css',
                            '/css/bootstrap-tokenfield.css',
                            '/bower_components/bootstrap/dist/css/bootstrap-datepicker.css',
                            '/assets/css/sumoselect.css',

                            )) !!}