{!! Minify::stylesheet(array('/assets/css/new/font-awesome.css',
                            '/assets/css/new/material-design-iconic-font.css',
                            '/assets/css/new/bootstrap.css',
                            '/assets/css/new/animate.css',
                            '/assets/css/new/layout.css',
                            '/assets/css/new/components.css',
                            '/assets/css/new/widgets.css',
                            '/assets/css/new/plugins.css',
                            '/assets/css/new/pages.css',
                            '/assets/css/new/bootstrap-extend.css',
                            '/css/bootstrap-timepicker.min.css',
                            '/assets/css/new/common.css',
                            '/assets/css/new/responsive.css',
                            '/assets/css/new/custom.css',
                            )) !!}