<div id="invoice_print">
    @if( isset($bill) && !empty($bill) )
        <table cellpadding="0" cellspacing="0" style=" max-width:100%;
                                                        margin:auto;
                                                        padding:30px;
                                                        /*border:1px solid #eee;
                                                        box-shadow:0 0 10px rgba(0, 0, 0, .15);*/
                                                        /*font-size:14px;*/
                                                        line-height:24px;
                                                        font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
                                                        color:#555;   width:100%;
                                                        line-height:inherit;
                                                        text-align:left;
                                                        max-width:600px;">
            <tr><td colspan="4" style="  padding:5px;vertical-align:top;text-align: center;font-weight:100;font-size:12px;">CASH MEMO / RETAIL INVOICE</td></tr>
            <tr><td colspan="4" style=" vertical-align:top;text-align: center;font-weight:bold;font-size:25px;">{!! $bill->vendor !!}</td></tr>
            <tr>
                <td colspan="4" style="  padding:5px;vertical-align:top;">
                    <table>
                        <tr>
                            <td height="60" class="title" style="vertical-align: top; padding: 5px; color: rgb(51, 51, 51); width: 282px; height:80px; font-size: 12px;">
                                {!! nl2br($bill->address) !!}<br>
                                {!! $bill->contact !!}
                            </td>

                            <td style="padding:5px 0px 5px 50px;vertical-align:top; width:300px;height:80px; font-size: 12px; ">
                                Invoice No.:{!! $bill->invoice_no !!}<br>
                                Generated By: {!! $bill->generated_by !!}<br>
                                Date: {!! $bill->invoice_date !!}<br><br>
                            </td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr>
                <td colspan="4">
                    <table style="min-height: 300px; display: block;">
                        <tr>
                            <td style="padding:5px;vertical-align:top;background:#eee;border-bottom:1px solid #ddd;
                            font-weight:bold; width:400px;">
                                Items
                            </td>

                            <td style="padding:5px;vertical-align:top;background:#eee;border-bottom:1px solid #ddd;
                        font-weight:bold; width:100px;">Qty</td>

                            <td style="padding:5px;
                            vertical-align:top;   background:#eee;
                            border-bottom:1px solid #ddd;
                            font-weight:bold; width:100px;text-align: right"> Price
                            </td>

                            <td style="  padding:5px;
                        vertical-align:top;   background:#eee;
                        border-bottom:1px solid #ddd;
                        font-weight:bold;">Amount
                            </td>
                        </tr>
                        @if( isset($items) && sizeof($items) > 0 )
                            @foreach( $items as $itm )
                                <tr>
                                    <td style="  padding:5px 5px 0px 5px;vertical-align:top;font-size:12px;">{!! $itm->item_name !!}</td>
                                    <td style="  padding:5px 5px 0px 5px;vertical-align:top;font-size:12px;">{!! $itm->quantity."".$itm->unit_name !!}</td>
                                    <td style="text-align: right;padding:5px 5px 0px 5px;vertical-align:top;font-size:12px;">{!! number_format($itm->rate,2) !!}</td>
                                    <td style="  padding:5px 5px 0px 5px;vertical-align:top;text-align:right;font-size:12px;">{!! number_format($itm->total,2) !!}</td>
                                </tr>
                            @endforeach
                        @endif
                    </table>
                </td>
            </tr>

            <tr>
                <td colspan="4"><hr style="margin-bottom: 10px !important;margin-top: 10px !important;"/></td>
            </tr>

            <tr class="item" style="height:15px">
                <td colspan="2" style="  padding:0 5px 0 5px; vertical-align:top; font-size:12px;">Sub Total</td>
                <td colspan="2" style="padding:0 5px 0 5px; vertical-align:top;text-align:right; font-size:12px">&#8377; <span id="sub_total">{!! number_format($bill->total,2) !!}</span></td>
            </tr>



            {{--Display taxes--}}



            <tr style="height:15px">
                <td style="  padding:5px;vertical-align:top;border-top:2px solid #ccc;font-weight:bold;text-align:left; ">
                    Total: &nbsp; &nbsp;
                </td>
                <td  colspan="3" style="  padding:5px;vertical-align:top;width:500px;  border-top:2px solid #ccc;font-weight:bold;text-align:right; ">
                    &#8377; {!! number_format($bill->total,2) !!}
                </td>
            </tr>

        </table>


    @else
        <span style="text-align:center;">Order detail not found.</span>
    @endif
</div>