<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Psy\\' => array($vendorDir . '/psy/psysh/src'),
    'PhpSpec' => array($vendorDir . '/phpspec/phpspec/src'),
    'PHPExcel' => array($vendorDir . '/phpoffice/phpexcel/Classes'),
    'Maatwebsite\\Excel\\' => array($vendorDir . '/maatwebsite/excel/src'),
    'JakubOnderka\\PhpConsoleHighlighter' => array($vendorDir . '/jakub-onderka/php-console-highlighter/src'),
    'JShrink' => array($vendorDir . '/tedivm/jshrink/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'Dotenv' => array($vendorDir . '/vlucas/phpdotenv/src'),
    'Diff' => array($vendorDir . '/phpspec/php-diff/lib'),
    'Bican\\Roles' => array($vendorDir . '/bican/roles/src'),
    'Aws' => array($vendorDir . '/aws/aws-sdk-php/src'),
);
