<?php return array(
    'root' => array(
        'name' => 'laravel/laravel',
        'pretty_version' => 'dev-master',
        'version' => 'dev-master',
        'reference' => '5b951132e293a2b7e3915049117322dc3350f48c',
        'type' => 'project',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'aws/aws-sdk-php' => array(
            'pretty_version' => '2.8.31',
            'version' => '2.8.31.0',
            'reference' => '64fa4b07f056e338a5f0f29eece75babaa83af68',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'aws/aws-sdk-php-laravel' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '90187392c1a79948a6c7a4bbf9cbe73dab5cc107',
            'type' => 'library',
            'install_path' => __DIR__ . '/../aws/aws-sdk-php-laravel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'barryvdh/laravel-debugbar' => array(
            'pretty_version' => 'v2.4.3',
            'version' => '2.4.3.0',
            'reference' => 'd7c88f08131f6404cb714f3f6cf0642f6afa3903',
            'type' => 'library',
            'install_path' => __DIR__ . '/../barryvdh/laravel-debugbar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'bican/roles' => array(
            'pretty_version' => '1.7.1',
            'version' => '1.7.1.0',
            'reference' => '5922d8c136f829d7799aca7869a8139011059961',
            'type' => 'library',
            'install_path' => __DIR__ . '/../bican/roles',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'classpreloader/classpreloader' => array(
            'pretty_version' => '2.0.0',
            'version' => '2.0.0.0',
            'reference' => '8c3c14b10309e3b40bce833913a6c0c0b8c8f962',
            'type' => 'library',
            'install_path' => __DIR__ . '/../classpreloader/classpreloader',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'danielstjules/stringy' => array(
            'pretty_version' => '1.10.0',
            'version' => '1.10.0.0',
            'reference' => '4749c205db47ee5b32e8d1adf6d9aff8db6caf3b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../danielstjules/stringy',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'devfactory/minify' => array(
            'pretty_version' => '1.0.14',
            'version' => '1.0.14.0',
            'reference' => '4785f08743bdccf075c53c919e4858a42c306fed',
            'type' => 'library',
            'install_path' => __DIR__ . '/../devfactory/minify',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'dnoegel/php-xdg-base-dir' => array(
            'pretty_version' => '0.1',
            'version' => '0.1.0.0',
            'reference' => '265b8593498b997dc2d31e75b89f053b5cc9621a',
            'type' => 'project',
            'install_path' => __DIR__ . '/../dnoegel/php-xdg-base-dir',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/cache' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1ca8f21980e770095a31456042471a57bc4c68fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/cache',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/dbal' => array(
            'pretty_version' => '2.13.9',
            'version' => '2.13.9.0',
            'reference' => 'c480849ca3ad6706a39c970cdfe6888fa8a058b8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/dbal',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/deprecations' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => '31610dbb31faa98e6b5447b62340826f54fbc4e9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/deprecations',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/event-manager' => array(
            'pretty_version' => '1.2.0',
            'version' => '1.2.0.0',
            'reference' => '95aa4cb529f1e96576f3fda9f5705ada4056a520',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/event-manager',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/inflector' => array(
            'pretty_version' => '1.4.4',
            'version' => '1.4.4.0',
            'reference' => '4bd5c1cdfcd00e9e2d8c484f79150f67e5d355d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/inflector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'doctrine/instantiator' => array(
            'pretty_version' => '1.5.0',
            'version' => '1.5.0.0',
            'reference' => '0a0fa9780f5d4e507415a065172d26a98d02047b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../doctrine/instantiator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'docusign/esign-client' => array(
            'pretty_version' => '3.0.1',
            'version' => '3.0.1.0',
            'reference' => '4e7d192783f3a1996203c1a087806385bd6c513f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../docusign/esign-client',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'fabiang/xmpp' => array(
            'pretty_version' => '0.7.0',
            'version' => '0.7.0.0',
            'reference' => 'd5fe3acc355f948a4dd0407a7840692f4cf133c3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../fabiang/xmpp',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzle/batch' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/common' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/guzzle' => array(
            'pretty_version' => 'v3.9.3',
            'version' => '3.9.3.0',
            'reference' => '0645b70d953bc1c067bbc8d5bc53194706b628d9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../guzzle/guzzle',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'guzzle/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/inflection' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/iterator' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/parser' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-async' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-backoff' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-curlauth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-error-response' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-history' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-md5' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-mock' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/plugin-oauth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/service' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'guzzle/stream' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v3.9.3',
            ),
        ),
        'illuminate/auth' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/broadcasting' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/bus' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/cache' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/config' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/console' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/container' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/contracts' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/cookie' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/database' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/encryption' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/events' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/exception' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/filesystem' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/foundation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/hashing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/html' => array(
            'pretty_version' => 'v5.0.0',
            'version' => '5.0.0.0',
            'reference' => '3d1009bb8e0f25720c914af5c1f4015dd373c9ef',
            'type' => 'library',
            'install_path' => __DIR__ . '/../illuminate/html',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'illuminate/http' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/log' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/mail' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/pagination' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/pipeline' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/queue' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/redis' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/routing' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/session' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/support' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/translation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/validation' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'illuminate/view' => array(
            'dev_requirement' => false,
            'replaced' => array(
                0 => 'v5.1.11',
            ),
        ),
        'imagine/imagine' => array(
            'pretty_version' => 'v0.7.1',
            'version' => '0.7.1.0',
            'reference' => 'a9a702a946073cbca166718f1b02a1e72d742daa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../imagine/imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-color' => array(
            'pretty_version' => 'v0.2',
            'version' => '0.2.0.0',
            'reference' => 'd5deaecff52a0d61ccb613bb3804088da0307191',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-color',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jakub-onderka/php-console-highlighter' => array(
            'pretty_version' => 'v0.3.2',
            'version' => '0.3.2.0',
            'reference' => '7daa75df45242c8d5b75a22c00a201e7954e4fb5',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jakub-onderka/php-console-highlighter',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'jeremeamia/superclosure' => array(
            'pretty_version' => '2.4.0',
            'version' => '2.4.0.0',
            'reference' => '5707d5821b30b9a07acfb4d76949784aaa0e9ce9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../jeremeamia/superclosure',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'kylekatarnls/update-helper' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '429be50660ed8a196e0798e5939760f168ec8ce9',
            'type' => 'composer-plugin',
            'install_path' => __DIR__ . '/../kylekatarnls/update-helper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laracasts/generators' => array(
            'pretty_version' => '1.1.7',
            'version' => '1.1.7.0',
            'reference' => '134fd33fcbde4799c4d22106ab4af5c23a8067e4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laracasts/generators',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'laravel/framework' => array(
            'pretty_version' => 'v5.1.11',
            'version' => '5.1.11.0',
            'reference' => 'e24a87cee3d12d42bc1b9ffa2821ef2ce22ef553',
            'type' => 'library',
            'install_path' => __DIR__ . '/../laravel/framework',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'laravel/laravel' => array(
            'pretty_version' => 'dev-master',
            'version' => 'dev-master',
            'reference' => '5b951132e293a2b7e3915049117322dc3350f48c',
            'type' => 'project',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/flysystem' => array(
            'pretty_version' => '1.1.10',
            'version' => '1.1.10.0',
            'reference' => '3239285c825c152bcc315fe0e87d6b55f5972ed1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/flysystem',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'league/mime-type-detection' => array(
            'pretty_version' => '1.12.0',
            'version' => '1.12.0.0',
            'reference' => 'c7f2872fb273bf493811473dafc88d60ae829f48',
            'type' => 'library',
            'install_path' => __DIR__ . '/../league/mime-type-detection',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maatwebsite/excel' => array(
            'pretty_version' => '2.0.11',
            'version' => '2.0.11.0',
            'reference' => '731487fda0e3e26c8701d8ee1aafc7b7429a95ce',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maatwebsite/excel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'maximebf/debugbar' => array(
            'pretty_version' => '1.13.1',
            'version' => '1.13.1.0',
            'reference' => 'afee79a236348e39a44cb837106b7c5b4897ac2a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../maximebf/debugbar',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'monolog/monolog' => array(
            'pretty_version' => '1.27.1',
            'version' => '1.27.1.0',
            'reference' => '904713c5929655dc9b97288b69cfeedad610c9a1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../monolog/monolog',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mtdowling/cron-expression' => array(
            'pretty_version' => 'v1.2.3',
            'version' => '1.2.3.0',
            'reference' => '9be552eebcc1ceec9776378f7dcc085246cacca6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mtdowling/cron-expression',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'natxet/cssmin' => array(
            'pretty_version' => 'v3.0.6',
            'version' => '3.0.6.0',
            'reference' => 'd5d9f4c3e5cedb1ae96a95a21731f8790e38f1dd',
            'type' => 'library',
            'install_path' => __DIR__ . '/../natxet/cssmin',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nesbot/carbon' => array(
            'pretty_version' => '1.39.1',
            'version' => '1.39.1.0',
            'reference' => '4be0c005164249208ce1b5ca633cd57bdd42ff33',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nesbot/carbon',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'nikic/php-parser' => array(
            'pretty_version' => 'v1.4.1',
            'version' => '1.4.1.0',
            'reference' => 'f78af2c9c86107aa1a34cd1dbb5bbe9eeb0d9f51',
            'type' => 'library',
            'install_path' => __DIR__ . '/../nikic/php-parser',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orchestra/contracts' => array(
            'pretty_version' => 'v3.1.14',
            'version' => '3.1.14.0',
            'reference' => '9923780345db5660586a72b48534ce44047fd4bc',
            'type' => 'library',
            'install_path' => __DIR__ . '/../orchestra/contracts',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orchestra/imagine' => array(
            'pretty_version' => 'v3.1.3',
            'version' => '3.1.3.0',
            'reference' => '57c3f2d228fca55bd1b32fe230776faf5d909225',
            'type' => 'library',
            'install_path' => __DIR__ . '/../orchestra/imagine',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orchestra/support-core' => array(
            'pretty_version' => 'v3.1.8',
            'version' => '3.1.8.0',
            'reference' => '3addbd757999fdf6b613d070c69bac5db5e24932',
            'type' => 'library',
            'install_path' => __DIR__ . '/../orchestra/support-core',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'orchestra/support-providers' => array(
            'pretty_version' => 'v3.1.8',
            'version' => '3.1.8.0',
            'reference' => 'fcf06025a21a05aaf0b28c86185dc419b792cbeb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../orchestra/support-providers',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'pda/pheanstalk' => array(
            'pretty_version' => 'v3.2.1',
            'version' => '3.2.1.0',
            'reference' => '57b6e76f1b06ca798e739a8dee92c2dac04fd170',
            'type' => 'library',
            'install_path' => __DIR__ . '/../pda/pheanstalk',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpdocumentor/reflection-common' => array(
            'pretty_version' => '2.2.0',
            'version' => '2.2.0.0',
            'reference' => '1d01c49d4ed62f25aa84a747ad35d5a16924662b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-common',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/reflection-docblock' => array(
            'pretty_version' => '5.3.0',
            'version' => '5.3.0.0',
            'reference' => '622548b623e81ca6d78b721c5e029f4ce664f170',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/reflection-docblock',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpdocumentor/type-resolver' => array(
            'pretty_version' => '1.6.1',
            'version' => '1.6.1.0',
            'reference' => '77a32518733312af16a44300404e945338981de3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpdocumentor/type-resolver',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpoffice/phpexcel' => array(
            'pretty_version' => '1.8.2',
            'version' => '1.8.2.0',
            'reference' => '1441011fb7ecdd8cc689878f54f8b58a6805f870',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpoffice/phpexcel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'phpspec/php-diff' => array(
            'pretty_version' => 'v1.0.2',
            'version' => '1.0.2.0',
            'reference' => '30e103d19519fe678ae64a60d77884ef3d71b28a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/php-diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpspec/phpspec' => array(
            'pretty_version' => '2.5.8',
            'version' => '2.5.8.0',
            'reference' => 'd8a153dcb52f929b448c0bf2cc19c7388951adb1',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/phpspec',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpspec/prophecy' => array(
            'pretty_version' => 'v1.10.3',
            'version' => '1.10.3.0',
            'reference' => '451c3cd1418cf640de218914901e51b064abb093',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpspec/prophecy',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-code-coverage' => array(
            'pretty_version' => '2.2.4',
            'version' => '2.2.4.0',
            'reference' => 'eabf68b476ac7d0f73793aada060f1c1a9bf8979',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-code-coverage',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-file-iterator' => array(
            'pretty_version' => '1.4.5',
            'version' => '1.4.5.0',
            'reference' => '730b01bc3e867237eaac355e06a36b85dd93a8b4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-file-iterator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-text-template' => array(
            'pretty_version' => '1.2.1',
            'version' => '1.2.1.0',
            'reference' => '31f8b717e51d9a2afca6c9f046f5d69fc27c8686',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-text-template',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-timer' => array(
            'pretty_version' => '1.0.9',
            'version' => '1.0.9.0',
            'reference' => '3dcf38ca72b158baf0bc245e9184d3fdffa9c46f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-timer',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/php-token-stream' => array(
            'pretty_version' => '1.4.12',
            'version' => '1.4.12.0',
            'reference' => '1ce90ba27c42e4e44e6d8458241466380b51fa16',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/php-token-stream',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit' => array(
            'pretty_version' => '4.8.36',
            'version' => '4.8.36.0',
            'reference' => '46023de9a91eec7dfb06cc56cb4e260017298517',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'phpunit/phpunit-mock-objects' => array(
            'pretty_version' => '2.3.8',
            'version' => '2.3.8.0',
            'reference' => 'ac8e7a3db35738d56ee9a76e78a4e03d97628983',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpunit/phpunit-mock-objects',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log-implementation' => array(
            'dev_requirement' => false,
            'provided' => array(
                0 => '1.0.0',
            ),
        ),
        'psy/psysh' => array(
            'pretty_version' => 'v0.5.2',
            'version' => '0.5.2.0',
            'reference' => 'aaf8772ade08b5f0f6830774a5d5c2f800415975',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psy/psysh',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'sebastian/comparator' => array(
            'pretty_version' => '1.2.4',
            'version' => '1.2.4.0',
            'reference' => '2b7424b55f5047b47ac6e5ccb20b2aea4011d9be',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/comparator',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/diff' => array(
            'pretty_version' => '1.4.3',
            'version' => '1.4.3.0',
            'reference' => '7f066a26a962dbe58ddea9f72a4e82874a3975a4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/diff',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/environment' => array(
            'pretty_version' => '1.3.8',
            'version' => '1.3.8.0',
            'reference' => 'be2c607e43ce4c89ecd60e75c6a85c126e754aea',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/environment',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/exporter' => array(
            'pretty_version' => '1.2.2',
            'version' => '1.2.2.0',
            'reference' => '42c4c2eec485ee3e159ec9884f95b431287edde4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/exporter',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/global-state' => array(
            'pretty_version' => '1.1.1',
            'version' => '1.1.1.0',
            'reference' => 'bc37d50fea7d017d3d340f230811c9f1d7280af4',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/global-state',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/recursion-context' => array(
            'pretty_version' => '1.0.5',
            'version' => '1.0.5.0',
            'reference' => 'b19cc3298482a335a95f3016d2f8a6950f0fbcd7',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/recursion-context',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'sebastian/version' => array(
            'pretty_version' => '1.0.6',
            'version' => '1.0.6.0',
            'reference' => '58b3a85e7999757d6ad81c787a1fbf5ff6c628c6',
            'type' => 'library',
            'install_path' => __DIR__ . '/../sebastian/version',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'spatie/laravel-permission' => array(
            'pretty_version' => '1.18.0',
            'version' => '1.18.0.0',
            'reference' => 'd02ac59023c04061e9298ec8b307601502cb9331',
            'type' => 'library',
            'install_path' => __DIR__ . '/../spatie/laravel-permission',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'swiftmailer/swiftmailer' => array(
            'pretty_version' => 'v5.4.12',
            'version' => '5.4.12.0',
            'reference' => '181b89f18a90f8925ef805f950d47a7190e9b950',
            'type' => 'library',
            'install_path' => __DIR__ . '/../swiftmailer/swiftmailer',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/console' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => '574cb4cfaa01ba115fc2fc0c2355b2c5472a4804',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/console',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/css-selector' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => '0b490439a4287f6502426bcb0418e707c2eebe5e',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/css-selector',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/debug' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => '4a7330f29b3d215f8bacf076689f9d1c3d568681',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/debug',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/dom-crawler' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => 'd905e1c5885735ee66af60c205429b9941f24752',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/dom-crawler',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/event-dispatcher' => array(
            'pretty_version' => 'v2.8.52',
            'version' => '2.8.52.0',
            'reference' => 'a77e974a5fecb4398833b0709210e3d5e334ffb0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/event-dispatcher',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/finder' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => '34226a3aa279f1e356ad56181b91acfdc9a2525c',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/finder',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-foundation' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => 'b67e5cbd2bf837fb3681f2c4965826d6c6758532',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-foundation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/http-kernel' => array(
            'pretty_version' => 'v2.7.52',
            'version' => '2.7.52.0',
            'reference' => '435064b3b143f79469206915137c21e88b56bfb9',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/http-kernel',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-ctype' => array(
            'pretty_version' => 'v1.33.0',
            'version' => '1.33.0.0',
            'reference' => 'a3cc8b044a6ea513310cbd48ef7333b384945638',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-ctype',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-mbstring' => array(
            'pretty_version' => 'v1.31.0',
            'version' => '1.31.0.0',
            'reference' => '85181ba99b2345b0ef10ce42ecac37612d9fd341',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-mbstring',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php56' => array(
            'pretty_version' => 'v1.20.0',
            'version' => '1.20.0.0',
            'reference' => '54b8cd7e6c1643d78d011f3be89f3ef1f9f4c675',
            'type' => 'metapackage',
            'install_path' => null,
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/process' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => 'eda637e05670e2afeec3842dcd646dce94262f6b',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/process',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/routing' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => '33bd5882f201f9a3b7dd9640b95710b71304c4fb',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/routing',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/translation' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => '1959c78c5a32539ef221b3e18a961a96d949118f',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/translation',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/var-dumper' => array(
            'pretty_version' => 'v2.7.51',
            'version' => '2.7.51.0',
            'reference' => '6f9271e94369db05807b261fcfefe4cd1aafd390',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/var-dumper',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'symfony/yaml' => array(
            'pretty_version' => 'v3.3.18',
            'version' => '3.3.18.0',
            'reference' => 'af615970e265543a26ee712c958404eb9b7ac93d',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/yaml',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
        'tecnick.com/tcpdf' => array(
            'pretty_version' => '6.0.099',
            'version' => '6.0.099.0',
            'reference' => '75e7ad39458e060d0cae6fcb7d50a2c9f3af1b01',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tecnick.com/tcpdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tedivm/jshrink' => array(
            'pretty_version' => 'v1.8.1',
            'version' => '1.8.1.0',
            'reference' => 'f76454d4c48ddae6354a2f0eeb16633d4e755c9a',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tedivm/jshrink',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'tijsverkoyen/css-to-inline-styles' => array(
            'pretty_version' => '1.5.5',
            'version' => '1.5.5.0',
            'reference' => '9753fc340726e327e4d48b7c0604f85475ae0bc3',
            'type' => 'library',
            'install_path' => __DIR__ . '/../tijsverkoyen/css-to-inline-styles',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'vlucas/phpdotenv' => array(
            'pretty_version' => 'v1.1.1',
            'version' => '1.1.1.0',
            'reference' => '0cac554ce06277e33ddf9f0b7ade4b8bbf2af3fa',
            'type' => 'library',
            'install_path' => __DIR__ . '/../vlucas/phpdotenv',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'webmozart/assert' => array(
            'pretty_version' => '1.12.1',
            'version' => '1.12.1.0',
            'reference' => '9be6926d8b485f55b9229203f962b51ed377ba68',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webmozart/assert',
            'aliases' => array(),
            'dev_requirement' => true,
        ),
    ),
);
